/**
 * 像素角色动作帧（14 列 × 22 行）
 * 字符：H发 S皮 E眼 B饰 C衣 L裤 F鞋 Y特效
 */

export const COLS = 14;
export const ROWS = 22;
export const SCALE = 4;

export const IDLE_A = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC....CCC..",
  "..CCC....CCC..",
  "...CC....CC...",
  "....CCCCCC....",
  "....CC..CC....",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

export const IDLE_B = [
  ".....HHHHHH...",
  "....HHHHHHHH..",
  "....HHSSSSHH..",
  "....HSSSSSSHE.",
  ".....SSSSSS...",
  ".....SSBBSS...",
  "....CCCCCCCC..",
  "...CCCCCCCCCC.",
  "...CCC....CCC.",
  "...CCC....CCC.",
  "....CC....CC..",
  ".....CCCCCC...",
  ".....CC..CC...",
  "....CCC..CCC..",
  "....CCC..CCC..",
  "....LLL..LLL..",
  "....LLL..LLL..",
  "....LL....LL..",
  "...LLL....LLL.",
  "...LL......LL.",
  "..FFF......FFF",
  "..FFF......FFF",
];

export const WALK_A = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC....CCC..",
  "..CCC....CCC..",
  "...CC....CC...",
  "....CCCCCC....",
  "...CCC..CC....",
  "..CCCC..CCC...",
  "..CCC...CCC...",
  "..LLL...LLL...",
  ".LLLL...LLL...",
  ".LL.....LL....",
  "LLL.....LLL...",
  "LL.......LL...",
  "FF.......FFF..",
  "FF.......FFF..",
];

export const WALK_B = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC....CCC..",
  "..CCC....CCC..",
  "...CC....CC...",
  "....CCCCCC....",
  "....CC..CCC...",
  "...CCC..CCCC..",
  "...CCC...CCC..",
  "...LLL...LLL..",
  "...LLL...LLLL.",
  "....LL.....LL.",
  "...LLL.....LLL",
  "...LL.......LL",
  "..FFF.......FF",
  "..FFF.......FF",
];

export const JUMP = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  ".CCCC....CCCC.",
  ".CCC......CCC.",
  "..CC......CC..",
  "...CCCCCCCC...",
  "....CC..CC....",
  "...CCC..CCC...",
  "..LLLL..LLLL..",
  "..LLL....LLL..",
  "..LL......LL..",
  ".LLL......LLL.",
  ".LL........LL.",
  "FFF........FFF",
  "..............",
  "..............",
];

export const LAND = [
  "..............",
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCCCCCCCCC..",
  "...CCCCCCCC...",
  "....CCCCCC....",
  "...CCCCCCCC...",
  "...CC....CC...",
  "..CCC....CCC..",
  "..LLL....LLL..",
  "..LLLL..LLLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
  "FFFFFFFFFFFFFF",
  "FFFFFFFFFFFFFF",
];

export const DEFEND = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "...SSBBSS.....",
  "..CCCCCCCCC...",
  ".CCCCCCCCCCC..",
  ".CCCCC..CCCC..",
  ".CCCC....CCC..",
  "..CCC....CC...",
  "...CCCCCCCC...",
  "....CC..CC....",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

/* ========== 普攻1：直拳 ========== */
export const ATK1_WIND = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "CCCCCCCCC.....",
  "CCCC..CCC.....",
  "SSS...CCC.....",
  "SS....CC......",
  "......CC......",
  "....CCCCCC....",
  "....CC..CC....",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

export const ATK1_HIT = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCC...SSYYYY",
  "..CCC..SSSYYYY",
  "..CC..SSSS.YYY",
  "...C.SSSS...Y.",
  "....CCCCCC....",
  "....CC..CC....",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

export const ATK1_REC = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCC..CCCC..",
  "..CCC....CCC..",
  "..CC......CC..",
  "...C......C...",
  "....CCCCCC....",
  "....CC..CC....",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

/* ========== 普攻2：侧踢 ========== */
export const ATK2_WIND = [
  "......HHHHHH..",
  ".....HHHHHHHH.",
  ".....HHSSSSHH.",
  ".....HSSSSSSHE",
  "......SSSSSS..",
  "......SSBBSS..",
  ".....CCCCCCCC.",
  "....CCCCCCCCCC",
  "....CCC..CCC..",
  ".....CC..CC...",
  "......CCCC....",
  ".....CC.......",
  "....LLL.......",
  "...LLLL.......",
  "..LLLL........",
  ".LLLL.........",
  "LLLL..........",
  "LLL...........",
  "FF............",
  "FF............",
  "..............",
  "..............",
];

export const ATK2_HIT = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "...CCCCCCC....",
  "....CCCC......",
  ".....CC.......",
  "..............",
  "LLLLYYYYYYYYY.",
  "LLL.YYYYYYYY..",
  "LL...YYYYY....",
  "L.....YYY.....",
  ".......Y......",
  "FF............",
  "FF............",
  "..............",
  "..............",
  "..............",
  "..............",
];

export const ATK2_REC = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC....CCC..",
  "...CC....CC...",
  "....CCCCCC....",
  "....CC..LLL...",
  "...CCC.LLLL...",
  "...CC.LLL.....",
  "...LLLL.......",
  "...LLL........",
  "..FFF.........",
  "..FF..........",
  "..............",
  "..............",
  "..............",
  "..............",
];

/* ========== 普攻3：大劈 ========== */
export const ATK3_WIND = [
  ".......YYYYY..",
  "......YYYYYY..",
  ".....YYYYYYY..",
  "....YYYYYYYY..",
  "...YHHHHHHY...",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSSY...",
  "...CCCCCCCY...",
  "..CCCC..CCY...",
  "..CCC....CY...",
  "...CC.....Y...",
  "....CCCCCC....",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

export const ATK3_HIT = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCYYYYYYYY",
  "..CC.YYYYYYYY.",
  "..C.YYYYYYY...",
  "...YYYYY......",
  "...YYYYCCCC...",
  "....YY.CC.CC..",
  "....Y.CCC.CCC.",
  "......CCC.CCC.",
  "......LLL.LLL.",
  "......LLL.LLL.",
  "......LL...LL.",
  ".....LLL...LLL",
  ".....LL.....LL",
  "....FFF.....FF",
  "....FFF.....FF",
];

export const ATK3_REC = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCC...",
  "..CCC....CCC..",
  "..CCC....CCCY.",
  "...CC....CCYY.",
  "....CCCCCC.Y..",
  "....CC..CC....",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

/* ========== 技能1：气弹 ========== */
export const SKL1_WIND = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  ".CCCCYYYYCCCC.",
  ".CCC.YYYY.CCC.",
  "..CC.YYYY..CC.",
  "...CCYYYYCC...",
  "....CYYYYC....",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

export const SKL1_HIT = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC..SSYYYYY",
  "..CCC.SSSYYYYY",
  "...CC.SSS.YYYY",
  "....CCCC...YYY",
  "....CC..CC..Y.",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

export const SKL1_REC = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC....CCC..",
  "..CCC....CCC..",
  "...CC....CC...",
  "....CCCCCC....",
  "....CC..CC....",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

/* ========== 技能2：吸掌 ========== */
export const SKL2_WIND = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "YY..CCCCCCC..Y",
  "YYYCCCC.CCCCYY",
  "YYCCC.....CCCY",
  "YCCC.......CCC",
  ".CC.........CC",
  "...CCCCCCCC...",
  "....CC..CC....",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

export const SKL2_HIT = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "SSSSCCCCCCYYYY",
  "SSSSSCCCC.YYYY",
  ".SSSSSCC..YYYY",
  "..SSSSS...YYY.",
  "...SSSS....YY.",
  "....CCCCCC.Y..",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

export const SKL2_REC = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  ".CCCC....CCCC.",
  ".CCC......CCC.",
  "..CC......CC..",
  "...CCCCCCCC...",
  "....CC..CC....",
  "...CCC..CCC...",
  "...CCC..CCC...",
  "...LLL..LLL...",
  "...LLL..LLL...",
  "...LL....LL...",
  "..LLL....LLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
];

/* ========== 技能3：升龙 ========== */
export const SKL3_WIND = [
  "........YYYY..",
  ".......YYYYY..",
  "......YYYYYY..",
  ".....YYYYYYY..",
  "....YHHHHHHY..",
  "...HHHHHHHHY..",
  "...HHSSSSHHY..",
  "...HSSSSSSHEY.",
  "....SSSSSS.Y..",
  "....SSBBSSY...",
  "...CCCCCCCY...",
  "..CCCCCCCC....",
  "..CCC..CCC....",
  "...CC..CC.....",
  "....CCCC......",
  "...LLL.LLL....",
  "..LLLL.LLLL...",
  "..LL.....LL...",
  ".FFF.....FFF..",
  ".FF.......FF..",
  "..............",
  "..............",
];

export const SKL3_HIT = [
  "...Y..Y..Y....",
  "..YYYYYYYYY...",
  ".YYYYYYYYYYY..",
  "..YHHHHHHHYY..",
  ".YHHHHHHHHYY..",
  ".YHHSSSSHHYY..",
  ".YHSSSSSSHEYY.",
  "..YSSSSSS.YYY.",
  "..YSSBBSSYYYY.",
  ".YCCCCCCCCYYY.",
  "YCCCCCCCCCCYY.",
  "YCCC....CCCYY.",
  ".YCC....CCYY..",
  "..YCCCCCCY....",
  "...YCC.CY.....",
  "..LLLL.LL.....",
  ".LLLL..LLL....",
  ".LL....LLL....",
  "FFF....FFF....",
  "FF......FF....",
  "..............",
  "..............",
];

export const SKL3_REC = [
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC....CCC..",
  "...CC....CC...",
  "....CCCCCC....",
  "....CC..CC....",
  "...CCC..CCC...",
  "...CCC..LLL...",
  "...LLL..LLL...",
  "..LLLL..LL....",
  "..LL....FF....",
  ".FFF....FF....",
  ".FF...........",
  "..............",
  "..............",
  "..............",
];

/* ========== 上段专属：手臂高举 ========== */
export const UP_WIND = [
  "........YYYY..",
  ".......YYYY...",
  "......YYYY....",
  ".....YYYY.....",
  "....YHHHHHH...",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC....CCC..",
  "...CC....CC...",
  "....CCCCCC....",
  "...LLL..LLL...",
  "..LLLL..LLLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FFF......FFF.",
  "..............",
  "..............",
];

export const UP_HIT = [
  "......Y.......",
  ".....YYY......",
  "....YYYYY.....",
  "...YYYYYYY....",
  "..YYYYYYYYY...",
  ".YYYHHHHHHYY..",
  ".YYHHHHHHHHY..",
  ".YYHHSSSSHHY..",
  ".YYHSSSSSSHEY.",
  "..YYSSSSSS.Y..",
  "..YYSSBBSSY...",
  ".YYCCCCCCCC...",
  "YYCCCCCCCCC...",
  "YYCC....CCC...",
  ".YCC....CC....",
  "..YCCCCCC.....",
  "...LLL.LLL....",
  "..LLLL.LLLL...",
  ".LLL.....LLL..",
  "FFF.......FFF.",
  "FF.........FF.",
  "..............",
];

export const UP_REC = [
  ".....YYYY.....",
  "....YYYYYY....",
  "...YHHHHHHY...",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC....CCC..",
  "...CC....CC...",
  "....CCCCCC....",
  "...LLL..LLL...",
  "..LLLL..LLLL..",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FF........FF.",
  "..............",
  "..............",
  "..............",
  "..............",
];

/* ========== 下段专属：贴地蹲扫 ========== */
export const DN_WIND = [
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "...SSBBSS.....",
  "..CCCCCCCCC...",
  ".CCCCCCCCCCC..",
  ".CCCC..CCCCC..",
  "..CCC....CCC..",
  "...CCCCCCCC...",
  "...LLL..LLL...",
  "..LLLL..LLLL..",
  ".FFF......FFF.",
  "FFFFFFFFFFFFFF",
  "FFFFFFFFFFFFFF",
];

export const DN_HIT = [
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSBBSS....",
  "..CCCCCCCCC...",
  "CCCCCCCCCCCCCC",
  "CCCC......YYYY",
  "CCC.......YYYY",
  "LLL........YYY",
  "LLL.........YY",
  "FFF..........Y",
  "FFFFFFFFFFFFFF",
  "FFFFFFFFFFFFFF",
  "..............",
];

export const DN_REC = [
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC....CCC..",
  "...CCCCCCCC...",
  "...LLL..LLL...",
  "..LLLL..LLLL..",
  ".FFF......FFF.",
  "FFFFFFFFFFFFFF",
  "FFFFFFFFFFFFFF",
  "..............",
  "..............",
];

/* ========== 空中专属：侧身踢 ========== */
export const AIR_WIND = [
  "..............",
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  ".CCC......CCC.",
  ".CC........CC.",
  "..CC......CC..",
  "...CCCCCCCC...",
  "....LL..LL....",
  "...LLLLLLLL...",
  "..LLL....LLL..",
  ".FFF......FFF.",
  ".FF........FF.",
  "..............",
  "..............",
  "..............",
  "..............",
];

export const AIR_HIT = [
  "..............",
  "...HHHHHH.....",
  "..HHHHHHHH....",
  "..HHSSSSHH....",
  "..HSSSSSSHE...",
  "...SSSSSS.....",
  "...SSBBSS.....",
  "..CCCCCCCCY...",
  ".CCCCCCCCCCYY.",
  "CCC......CCYYY",
  "CC........CYYY",
  ".CC......CCYY.",
  "..CCCCCCCCY...",
  "...LL..LL.....",
  "..LLLLLLLL....",
  ".LLL....LLLY..",
  "FFF......FFFY.",
  "FF........FF..",
  "..............",
  "..............",
  "..............",
  "..............",
];

export const AIR_REC = [
  "..............",
  "....HHHHHH....",
  "...HHHHHHHH...",
  "...HHSSSSHH...",
  "...HSSSSSSHE..",
  "....SSSSSS....",
  "....SSBBSS....",
  "...CCCCCCCC...",
  "..CCCCCCCCCC..",
  "..CCC....CCC..",
  "...CC....CC...",
  "....CCCCCC....",
  "....LL..LL....",
  "...LLLLLLLL...",
  "..LL......LL..",
  ".FFF......FFF.",
  ".FF........FF.",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
];

// 兼容旧名字
export const ATTACK_1 = ATK1_WIND;
export const ATTACK_2 = ATK1_HIT;
export const ATTACK_3 = ATK1_REC;
export const SKILL_1 = SKL1_WIND;
export const SKILL_2 = SKL1_HIT;

export const DASH = [
  "..HHHHHH......",
  ".HHHHHHHH.....",
  ".HHSSSSHH.....",
  ".HSSSSSSHE....",
  "..SSSSSS......",
  "..SSBBSS......",
  ".CCCCCCCCC....",
  "CCCCCCCCCCCC..",
  "CCCC....CCCC..",
  "CCC......CCC..",
  "CC........CC..",
  ".CCCCCCCCCC...",
  "..CC....CC....",
  ".CCC....CCC...",
  "LLLL....LLLL..",
  "LLL......LLL..",
  "LL........LL..",
  "FFF......FFF..",
  "FF........FF..",
  "..............",
  "..............",
  "..............",
];

export const HIT = [
  "...HHHHHH.....",
  "..HHHHHHHH....",
  "..HHSSSSHH....",
  "..HSSSSSSHE...",
  "...SSSSSS.....",
  "...SSBBSS.....",
  "..CCCCCCCC....",
  ".CCC....CCC...",
  ".CC......CC...",
  "..C......C....",
  "...CCCCCC.....",
  "....CC.CC.....",
  "...CCC.CCC....",
  "..LLL...LLL...",
  "..LL.....LL...",
  ".LLL.....LLL..",
  ".LL.......LL..",
  "FFF.......FFF.",
  "FF.........FF.",
  "..............",
  "..............",
  "..............",
];

export const DEAD = [
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
  ".HHHSSSBCCCCLL",
  "HHHHSSSSCCCCLL",
  "HHHSSSSECCCCLF",
  ".HHSSSS.CCCCFF",
  "..............",
  "..............",
  "..............",
  "..............",
  "..............",
];
